package com.example.taskmanager.ai;

import com.example.taskmanager.dto.AiTaskSuggestionResponse;

/**
 * Contract for producing task suggestions from free-form text.
 */
public interface AiTaskSuggestionClient {
	/**
	 * Returns a structured task suggestion generated by an AI model.
	 */
	AiTaskSuggestionResponse suggestTask(String userPrompt);
}
