package com.example.taskmanager.model;

import java.time.LocalDate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity representing a managed task item.
 */
@Entity
@Table(name = "tasks")
public class Task {

	// Primary key generated by the database.
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	// Required short label for the task.
	@Column(nullable = false)
	private String title;

	// Optional longer explanation of work to perform.
	@Column(length = 2000)
	private String description;

	// Optional target completion date.
	private LocalDate dueDate;

	// Priority value persisted as a readable string.
	@Enumerated(EnumType.STRING)
	@Column(nullable = false)
	private Priority priority;

	// Workflow state persisted as a readable string.
	@Enumerated(EnumType.STRING)
	@Column(nullable = false)
	private TaskStatus status;

	/** Returns the database identifier for this task. */
	public Long getId() {
		return id;
	}

	/** Sets the database identifier (typically managed by JPA). */
	public void setId(Long id) {
		this.id = id;
	}

	/** Returns the task title. */
	public String getTitle() {
		return title;
	}

	/** Sets the task title. */
	public void setTitle(String title) {
		this.title = title;
	}

	/** Returns the optional task description. */
	public String getDescription() {
		return description;
	}

	/** Sets the optional task description. */
	public void setDescription(String description) {
		this.description = description;
	}

	/** Returns the optional due date. */
	public LocalDate getDueDate() {
		return dueDate;
	}

	/** Sets the optional due date. */
	public void setDueDate(LocalDate dueDate) {
		this.dueDate = dueDate;
	}

	/** Returns the selected priority level. */
	public Priority getPriority() {
		return priority;
	}

	/** Sets the selected priority level. */
	public void setPriority(Priority priority) {
		this.priority = priority;
	}

	/** Returns the current workflow status. */
	public TaskStatus getStatus() {
		return status;
	}

	/** Sets the current workflow status. */
	public void setStatus(TaskStatus status) {
		this.status = status;
	}
}
